modLoader="javafml"
loaderVersion="*"
license="MIT"
issueTrackerURL="${issues_url}"
sourcesUrl="${sources_url}"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_display_name}"
displayURL="${homepage_url}"
logoFile="structure_layout_optimizer.png"
logoBlur=false
authors="TelepathicGrunt"
description='''${mod_description}'''

[dependencies]
"${mod_id}" = [
    { modId = "forge", mandatory = true, versionRange = "[43.4.0,)", ordering = "NONE", side = "BOTH" },
    { modId = "minecraft", mandatory = true, versionRange = "[1.19.2,1.20)", ordering = "NONE", side = "BOTH" },
    { modId = "cloth_config", mandatory = true, versionRange = "*", ordering = "NONE", side = "BOTH" },
]

[features]
"${mod_id}" = { java_version = "[${java_version},)" }
