org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# Common
minecraft_version=26.1
neoform_version=26.1-1

# NeoForge
neoforge_version=26.1.0.1-beta

# Fabric
fabric_loader_version=0.18.4
fabric_api_version=0.144.0+26.1

# MC dependencies
jetbrains_annotations_version=26.0.1
mixin_version=0.15.4+mixin.0.8.7
mixin_extras_version=0.4.1
asm_version=9.7

## Mod Properties
mod_id=structure_layout_optimizer
mod_name=Structure Layout Optimizer
mod_version=1.1.4
mod_description=An attempt at optimizing jigsaw generation
sources_url=https://github.com/TelepathicGrunt/StructureLayoutOptimizer
issues_url=https://github.com/TelepathicGrunt/StructureLayoutOptimizer/issues
license_url=https://github.com/TelepathicGrunt/StructureLayoutOptimizer/blob/HEAD/LICENSE.txt
homepage_url=https://www.curseforge.com/projects/1087831

# Publishing
mod_group_id=telepathicgrunt.structure_layout_optimizer
curseforge_id=1087831
modrinth_id=ayPU0OHc

# Libraries
resourceful_config_minecraft_version=26.1
resourceful_config_version=4.0.0
mod_menu_version=18.0.0-alpha.7
