name: Build Status

on:
  push:
    branches:
      - '*'
  pull_request:

env:
  JAVA_VERSION: 17
  JVM_VENDOR: 'microsoft'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # build
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JVM_VENDOR }}
          cache: 'gradle'
      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew assemble --rerun-tasks

      # store results
      - name: Upload build artifacts (Common)
        continue-on-error: true
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-Common-${{ github.sha }}
          path: |
            common/build/libs/*.jar
      - name: Upload build artifacts (Fabric)
        continue-on-error: true
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-Fabric-${{ github.sha }}
          path: |
            fabric/build/libs/*.jar
      - name: Upload build artifacts (NeoForge)
        continue-on-error: true
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-Forge-${{ github.sha }}
          path: |
            forge/build/libs/*.jar

      # run tests
#      - name: Run tests
#        run: ./gradlew check
